"use client";

import { useEffect, useState } from "react";
import { Check, ChevronRight, ReceiptText } from "lucide-react";

type Row=Record<string,any>;
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);return b}
function money(v:any){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(v||0))}
function invoiceStatus(v:string){return ({DRAFT:"Entwurf",REVIEW:"Rechnungsvorschlag",APPROVED:"Freigegeben",SENT:"Offen",PARTIALLY_PAID:"Teilbezahlt",PAID:"Bezahlt / Archiv",OVERDUE:"Überfällig",CANCELLED:"Storniert"} as Row)[v]||v}

export default function BillingWorkspace({user}:{user:Row}){
 const[invoices,setInvoices]=useState<Row[]>([]),[orders,setOrders]=useState<Row[]>([]),[reports,setReports]=useState<Row[]>([]),[preview,setPreview]=useState<Row|null>(null),[invoiceDetail,setInvoiceDetail]=useState<Row|null>(null),[error,setError]=useState("");
 async function load(){const[i,o,r]=await Promise.all([api("/api/billing"),api("/api/orders"),api("/api/reports")]);setInvoices(i);setOrders(o);setReports(r)}
 useEffect(()=>{load()},[]);
 const reviewO=orders.filter(x=>x.status==="READY_FOR_REVIEW"),readyO=orders.filter(x=>x.status==="COMPLETED"&&!invoices.some(i=>i.orderId===x.id&&i.status!=="CANCELLED")),reviewR=reports.filter(x=>x.status==="READY_FOR_REVIEW"),readyR=reports.filter(x=>x.status==="APPROVED"&&!x.invoices?.some((i:Row)=>i.status!=="CANCELLED"));
 const canReview=!!user.permissions?.BILLING?.edit;
 async function openPreview(source:Row){setError("");try{setPreview(await api("/api/billing/preview",{method:"POST",body:JSON.stringify(source)}))}catch(x:any){setError(x.message)}}
 async function approve(){if(!preview)return;try{const body=preview.source.kind==="order"?{orderId:preview.source.id}:{reportId:preview.source.id};await api("/api/billing/review",{method:"POST",body:JSON.stringify(body)});setPreview(null);await load()}catch(x:any){setError(x.message)}}
 async function createInvoice(){if(!preview)return;try{const body=preview.source.kind==="order"?{orderId:preview.source.id}:{reportId:preview.source.id};const created=await api("/api/billing",{method:"POST",body:JSON.stringify(body)});setPreview(null);setInvoiceDetail(created);await load()}catch(x:any){setError(x.message)}}
 return <div className="page-wrap"><div className="page-head"><div><p className="eyebrow">Finanzen</p><h1>Abrechnung</h1><p>Rechnungsprüfung, Freigabe, Rechnungsvorschläge und offene Forderungen.</p></div></div>{error&&<div className="form-error">{error}</div>}
 <section className="panel"><div className="panel-head"><div><h2>Rechnungsprüfung</h2><p>Vorgang öffnen, geplante Abrechnung prüfen und anschließend freigeben.</p></div><span className="count-badge">{reviewO.length+reviewR.length}</span></div>{[...reviewO.map(x=>({...x,_kind:"order"})),...reviewR.map(x=>({...x,_kind:"report"}))].map((x:Row)=><button className="review-row" key={`${x._kind}-${x.id}`} onClick={()=>openPreview(x._kind==="order"?{orderId:x.id}:{reportId:x.id})}><div><b>{x.number} · {x.customer?.name}</b><small>{x.title} · {x._kind==="order"?"Auftrag":"Rapport"}</small></div><span className="status-pill">Prüfen</span><ChevronRight size={17}/></button>)}{!reviewO.length&&!reviewR.length&&<div className="empty-row"><span>Nichts wartet auf Rechnungsprüfung.</span></div>}</section>
 <section className="panel"><div className="panel-head"><div><h2>Freigegeben zur Rechnung</h2><p>Auch hier wird der geplante Rechnungsinhalt zuerst angezeigt.</p></div></div>{readyO.map(x=><button className="review-row" key={x.id} onClick={()=>openPreview({orderId:x.id})}><div><b>{x.number} · {x.customer?.name}</b><small>{x.title}</small></div><span className="status-pill">Rechnung vorbereiten</span><ChevronRight size={17}/></button>)}{readyR.map(x=><button className="review-row" key={x.id} onClick={()=>openPreview({reportId:x.id})}><div><b>{x.number} · {x.customer?.name}</b><small>{x.title} · Rapport</small></div><span className="status-pill">Rechnung vorbereiten</span><ChevronRight size={17}/></button>)}{!readyO.length&&!readyR.length&&<div className="empty-row"><span>Keine freigegebenen Vorgänge.</span></div>}</section>
 <section className="panel"><div className="panel-head"><div><h2>Rechnungen</h2><p>Rechnungsvorschläge und offene Posten können wieder geöffnet werden.</p></div></div>{invoices.length?invoices.map(x=><button className="invoice-row" key={x.id} onClick={()=>setInvoiceDetail(x)}><div><b>{x.number} · {x.customer?.name}</b><small>{x.order?.title||x.report?.title||"Rechnung"}</small></div><span className="status-pill">{invoiceStatus(x.status)}</span><strong>{money(x.grossTotal)}</strong><ChevronRight size={17}/></button>):<div className="empty-row"><span>Noch keine Rechnungen.</span></div>}</section>
 {preview&&<div className="drawer-backdrop modal-backdrop" onMouseDown={()=>setPreview(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">Geplante Abrechnung</p><h2>{preview.source.number} · {preview.source.title}</h2><p>{preview.source.customer?.name}</p></div><button className="icon-btn" onClick={()=>setPreview(null)}>×</button></div><div className="table-card"><div className="table-head" style={{gridTemplateColumns:"1fr 90px 110px 110px"}}><span>Position</span><span>Menge</span><span>Einzelpreis</span><span>Gesamt</span></div>{preview.positions?.map((p:Row,i:number)=><div className="table-row" style={{gridTemplateColumns:"1fr 90px 110px 110px"}} key={i}><div><b>{p.description}</b><small>{p.source}</small></div><span>{Number(p.quantity).toLocaleString("de-DE")} {p.unit}</span><span>{money(p.unitPrice)}</span><strong>{money(Number(p.quantity)*Number(p.unitPrice))}</strong></div>)}</div><div className="quote-summary"><span>Netto <b>{money(preview.netTotal)}</b></span><span>USt. <b>{money(preview.taxTotal)}</b></span><strong>Brutto {money(preview.grossTotal)}</strong></div>{preview.positions?.length===0&&<div className="form-error">Es gibt noch keine abrechenbaren Positionen.</div>}<div className="button-row spaced">{((preview.source.kind==="order"&&reviewO.some(x=>x.id===preview.source.id))||(preview.source.kind==="report"&&reviewR.some(x=>x.id===preview.source.id)))&&<button className="primary-btn" disabled={!canReview||!preview.positions?.length} onClick={approve}><Check size={16}/>Zur Rechnung freigeben</button>}{((preview.source.kind==="order"&&readyO.some(x=>x.id===preview.source.id))||(preview.source.kind==="report"&&readyR.some(x=>x.id===preview.source.id)))&&<button className="primary-btn" disabled={!preview.positions?.length} onClick={createInvoice}><ReceiptText size={16}/>Rechnungsvorschlag erstellen</button>}<button className="secondary-btn" onClick={()=>setPreview(null)}>Schließen</button></div>{!canReview&&<small>Für die Freigabe ist Bearbeitungsrecht im Modul Abrechnung erforderlich.</small>}</div></div>}
 {invoiceDetail&&<div className="drawer-backdrop modal-backdrop" onMouseDown={()=>setInvoiceDetail(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">{invoiceStatus(invoiceDetail.status)}</p><h2>{invoiceDetail.number}</h2><p>{invoiceDetail.customer?.name}</p></div><button className="icon-btn" onClick={()=>setInvoiceDetail(null)}>×</button></div><div className="table-card"><div className="table-head" style={{gridTemplateColumns:"1fr 90px 110px 110px"}}><span>Position</span><span>Menge</span><span>Einzelpreis</span><span>Gesamt</span></div>{invoiceDetail.items?.map((p:Row)=><div className="table-row" style={{gridTemplateColumns:"1fr 90px 110px 110px"}} key={p.id}><div><b>{p.description}</b><small>USt. {Number(p.taxRate).toLocaleString("de-DE")} %</small></div><span>{Number(p.quantity).toLocaleString("de-DE")} {p.unit}</span><span>{money(p.unitPrice)}</span><strong>{money(Number(p.quantity)*Number(p.unitPrice))}</strong></div>)}</div><div className="quote-summary"><span>Netto <b>{money(invoiceDetail.netTotal)}</b></span><span>USt. <b>{money(invoiceDetail.taxTotal)}</b></span><strong>Brutto {money(invoiceDetail.grossTotal)}</strong></div><button className="secondary-btn full" onClick={()=>setInvoiceDetail(null)}>Schließen</button></div></div>}
 </div>
}
