"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronRight, Move, Trash2, Wrench } from "lucide-react";

type Row = Record<string, any>;

async function api(path:string, init?:RequestInit){const r=await fetch(path,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);return b}
function ymd(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function time(v:any){return v?new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"–"}
function hours(v:any){return (Number(v||0)/60).toLocaleString("de-DE",{maximumFractionDigits:2})}
function initials(v:string=""){return v.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"KR"}
function absenceType(v:string){return ({VACATION:"Urlaub",SICK:"Krank",TRAINING:"Fortbildung",TIME_OFF:"Zeitausgleich",OTHER:"Gesperrt"} as Row)[v]||v}

export default function PlanningWorkspace(){
 const [data,setData]=useState<Row|null>(null),[date,setDate]=useState(ymd(new Date())),[dragOrder,setDragOrder]=useState<Row|null>(null),[dragAssignment,setDragAssignment]=useState<Row|null>(null),[selectedOrder,setSelectedOrder]=useState<Row|null>(null),[detail,setDetail]=useState<Row|null>(null),[absence,setAbsence]=useState(false),[error,setError]=useState("");
 async function load(){setData(await api("/api/planning"))}
 useEffect(()=>{load()},[]);
 const hoursList=useMemo(()=>Array.from({length:15},(_,i)=>i+6),[]);
 if(!data)return <div className="page-wrap"><p>Einsatzplanung wird geladen …</p></div>;
 const openOrders=data.orders.filter((x:Row)=>!x.assignments?.length&&!x.scheduledAt);
 const dayStart=new Date(`${date}T00:00:00`),dayEnd=new Date(`${date}T23:59:59`);
 const assignments=data.orders.flatMap((o:Row)=>o.assignments.map((a:Row)=>({...a,order:o}))).filter((a:Row)=>new Date(a.startsAt)<=dayEnd&&new Date(a.endsAt)>=dayStart);
 async function place(userId:string,h:number){const start=new Date(`${date}T${String(h).padStart(2,"0")}:00:00`);setError("");try{if(dragAssignment){const duration=new Date(dragAssignment.endsAt).getTime()-new Date(dragAssignment.startsAt).getTime();await api("/api/planning",{method:"POST",body:JSON.stringify({action:"move",assignmentId:dragAssignment.id,userId,startsAt:start.toISOString(),endsAt:new Date(start.getTime()+duration).toISOString()})})}else{const order=dragOrder||selectedOrder;if(!order)return;const mins=Number(order.plannedMinutes||60);await api("/api/planning",{method:"POST",body:JSON.stringify({action:"assign",orderId:order.id,userId,startsAt:start.toISOString(),endsAt:new Date(start.getTime()+mins*60000).toISOString()})})}setDragAssignment(null);setDragOrder(null);setSelectedOrder(null);await load()}catch(x:any){setError(x.message)}}
 async function removeAssignment(){if(!detail)return;try{await api("/api/planning",{method:"POST",body:JSON.stringify({action:"remove",assignmentId:detail.id})});setDetail(null);await load()}catch(x:any){setError(x.message)}}
 async function moveFromModal(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!detail)return;const f=new FormData(e.currentTarget);try{await api("/api/planning",{method:"POST",body:JSON.stringify({action:"move",assignmentId:detail.id,userId:f.get("userId"),startsAt:new Date(String(f.get("startsAt"))).toISOString(),endsAt:new Date(String(f.get("endsAt"))).toISOString()})});setDetail(null);await load()}catch(x:any){setError(x.message)}}
 async function addAbs(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/planning",{method:"POST",body:JSON.stringify({action:"absence",...Object.fromEntries(f.entries())})});setAbsence(false);await load()}catch(x:any){setError(x.message)}}
 return <div className="page-wrap"><div className="page-head"><div><p className="eyebrow">Kalender</p><h1>Einsatzplanung</h1><p>06:00–20:00 Uhr, Mitarbeiter horizontal und offene Aufträge rechts.</p></div><div className="button-row"><label className="field"><span>Tag</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="secondary-btn" onClick={()=>setAbsence(true)}>Abwesenheit</button></div></div>{error&&<div className="form-error">{error}</div>}
 <div className="planner-shell"><div className="planner-scroll"><div className="planner-grid" style={{gridTemplateColumns:`70px repeat(${Math.max(1,data.users.length)}, minmax(160px,1fr))`}}><div className="planner-corner">Zeit</div>{data.users.map((u:Row)=><div className="planner-user" key={u.id}><div className="avatar">{initials(u.fullName)}</div><b>{u.fullName}</b></div>)}{hoursList.map(h=><div key={`row-${h}`} style={{display:"contents"}}><div className="planner-time">{String(h).padStart(2,"0")}:00</div>{data.users.map((u:Row)=><div key={`${u.id}-${h}`} className="planner-cell" onDragOver={e=>e.preventDefault()} onDrop={()=>place(u.id,h)} onClick={()=>selectedOrder&&place(u.id,h)}>{assignments.filter((a:Row)=>a.userId===u.id&&new Date(a.startsAt).getHours()===h).map((a:Row)=><button draggable className="job-block" key={a.id} onDragStart={e=>{e.stopPropagation();setDragAssignment(a);setDragOrder(null)}} onClick={e=>{e.stopPropagation();setDetail(a)}}><b>{a.order.number}</b><span>{a.order.customer?.name}</span><small>{time(a.startsAt)}–{time(a.endsAt)}</small></button>)}{data.absences.filter((a:Row)=>a.userId===u.id&&new Date(a.startsAt)<new Date(`${date}T${String(h+1).padStart(2,"0")}:00:00`)&&new Date(a.endsAt)>new Date(`${date}T${String(h).padStart(2,"0")}:00:00`)).map((a:Row)=><div className="absence-block" key={a.id}>{absenceType(a.type)}</div>)}</div>)}</div>)}</div></div>
 <aside className="planner-open"><h3>Offene Aufträge</h3><p>Ziehen oder antippen und anschließend eine Startzeit auswählen.</p>{openOrders.length?openOrders.map((o:Row)=><div draggable className={`open-job ${selectedOrder?.id===o.id?"selected":""}`} onDragStart={()=>{setDragOrder(o);setDragAssignment(null)}} onClick={()=>setSelectedOrder(selectedOrder?.id===o.id?null:o)} key={o.id}><b>{o.number}</b><span>{o.customer?.name}</span><small>{o.title} · {hours(o.plannedMinutes||60)} h</small></div>):<div className="empty-row"><span>Keine unzugeordneten Aufträge.</span></div>}</aside></div>
 {data.warnings?.length>0&&<section className="panel"><div className="panel-head"><div><h2>Planungswarnungen</h2><p>Konflikte und unbesetzte Termine</p></div></div>{data.warnings.map((w:Row,i:number)=><div className="form-error" key={i}>{w.message}</div>)}</section>}
 {detail&&<div className="drawer-backdrop modal-backdrop" onMouseDown={()=>setDetail(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">Geplanter Einsatz</p><h2>{detail.order.number} · {detail.order.title}</h2></div><button className="icon-btn" onClick={()=>setDetail(null)}>×</button></div><div className="fact-grid"><div><span>Kunde</span><b>{detail.order.customer?.name}</b></div><div><span>Mitarbeiter</span><b>{detail.user?.fullName}</b></div><div><span>Beginn</span><b>{time(detail.startsAt)}</b></div><div><span>Ende</span><b>{time(detail.endsAt)}</b></div></div><form onSubmit={moveFromModal}><label className="field"><span>Mitarbeiter</span><select name="userId" defaultValue={detail.userId}>{data.users.map((u:Row)=><option key={u.id} value={u.id}>{u.fullName}</option>)}</select></label><label className="field"><span>Von</span><input name="startsAt" type="datetime-local" defaultValue={new Date(detail.startsAt).toISOString().slice(0,16)} required/></label><label className="field"><span>Bis</span><input name="endsAt" type="datetime-local" defaultValue={new Date(detail.endsAt).toISOString().slice(0,16)} required/></label><div className="button-row"><button className="primary-btn"><Move size={16}/>Verschieben</button><button type="button" className="secondary-btn" onClick={async()=>{const full=await api(`/api/orders/${detail.order.id}`);alert(`${full.number} · ${full.title}\n${full.customer?.name||""}\n${full.description||""}`)}}><Wrench size={16}/>Auftrag öffnen</button><button type="button" className="secondary-btn" onClick={removeAssignment}><Trash2 size={16}/>Aus Kalender entfernen</button></div></form></div></div>}
 {absence&&<div className="drawer-backdrop modal-backdrop" onMouseDown={()=>setAbsence(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>Abwesenheit eintragen</h2><button className="icon-btn" onClick={()=>setAbsence(false)}>×</button></div><form onSubmit={addAbs}><label className="field"><span>Mitarbeiter</span><select name="userId">{data.users.map((u:Row)=><option key={u.id} value={u.id}>{u.fullName}</option>)}</select></label><label className="field"><span>Grund</span><select name="type"><option value="VACATION">Urlaub</option><option value="SICK">Krank</option><option value="TRAINING">Fortbildung</option><option value="TIME_OFF">Zeitausgleich</option><option value="OTHER">Sonstiges</option></select></label><label className="field"><span>Von</span><input name="startsAt" type="datetime-local" required/></label><label className="field"><span>Bis</span><input name="endsAt" type="datetime-local" required/></label><label className="field"><span>Notiz</span><input name="note"/></label><button className="primary-btn full">Sperren</button></form></div></div>}
 </div>
}
